### ISSUE TITLE
ERROR DealerClient:112 - Failed handling request.

### ISSUE THREAD

**Issue by caschual** [librespot-org/librespot-java#283] opened 2020-12-31 11:29 UTC
Dear all,
since a while now I am facing the issue that I am no longer able to connect Spotify via spocon service. The service is started and running without any issues according to status information.
However, each time I am triggering a connection via one of my handheld devices the following error is generated reproducibly:

user@sandbox:~$ journalctl --no-pager -f -u spocon
-- Logs begin at Thu 2020-09-24 21:27:11 CEST. --
Dez 31 12:13:07 sandbox systemd[1]: spocon.service: Main process exited, code=exited, status=143/n/a
Dez 31 12:13:07 sandbox systemd[1]: spocon.service: Failed with result 'exit-code'.
Dez 31 12:13:07 sandbox systemd[1]: Stopped SpoCon.
Dez 31 12:13:07 sandbox systemd[1]: Starting SpoCon...
Dez 31 12:13:07 sandbox sh[23056]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Dez 31 12:13:07 sandbox sh[23056]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=119 time=8.85 ms
Dez 31 12:13:07 sandbox sh[23056]: --- spotify.com ping statistics ---
Dez 31 12:13:07 sandbox sh[23056]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Dez 31 12:13:07 sandbox sh[23056]: rtt min/avg/max/mdev = 8.851/8.851/8.851/0.000 ms
Dez 31 12:13:07 sandbox systemd[1]: Started SpoCon.
Dez 31 12:13:20 sandbox java[23057]: 2020-12-31 12:13:20,332 ERROR DealerClient:112 - Failed handling request. {key: 1144dff2-9ffa-41f4-8eab-308e66d8c610}
Dez 31 12:13:20 sandbox java[23057]: java.lang.IllegalStateException: null
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.player.StateWrapper.getCurrentPlayableOrThrow(StateWrapper.java:558) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.player.Player.loadTrack(Player.java:254) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.player.Player.loadSession(Player.java:239) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.player.Player.handleTransferState(Player.java:370) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.player.Player.command(Player.java:300) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Dez 31 12:13:20 sandbox java[23057]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Dez 31 12:13:20 sandbox java[23057]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Dez 31 12:13:20 sandbox java[23057]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Dez 31 12:13:20 sandbox java[23057]:         at java.lang.Thread.run(Thread.java:834) [?:?]

I could not find anything pointing to a similar error. Any help appreciated.

Thanks and a happy new year!
Cornelius

**Comment by devgianlu** [comment] 2020-12-31 11:43
Duplicate of #281.

Happy new year!

**Closed by devgianlu** 2020-12-31 11:43 UTC
