### ISSUE TITLE
IllegalStateException when seeking rapidly after changing songs

### ISSUE THREAD

**Issue by Iscle** [librespot-org/librespot-java#216] opened 2020-04-28 16:56 UTC
I've been playing with the lib, trying to break it, over Spotify Connect. I've tried to rapidly change tracks and seek for a track position rapidly when it still didn't change, and I've managed to trigger an IllegalStateException in the CircularBuffer.

This does not affect too much the behaviour. The next song will play, but you'll loose the seeked position and just start from 0:00.

I've also noticed that when an exception is thrown, the log becomes mangled up (I assume because the exception is being printed from another thread).

This is the log from the beginning of the execution, to the end: https://del.dog/winginerfe

(This was taken from a build from the dev branch as of right now)

**Comment by devgianlu** [comment] 2020-04-29 09:24
Should be fixed or at least I couldn't reproduce it.

**Comment by Iscle** [comment] 2020-04-29 13:00
I've just tested it, and I managed to reproduce it again. I'll try to detail the steps a bit more closely so you might have a chance to reproduce it. I know this issue is a bit edge case, but at least it's good to know so that this can be a 100% bug-free project.

First I start playing a song, I'm doing it from a playlist. Then, from the Windows client, I click on next and immediately after I click on the seek bar to seek to a new position. I do this before the song has changed, and before the Windows UI has updated. Then, the exception gets thrown.

The log is also misbehaving, just as before.

The log is the same as before, so I won't upload it again. However, if you need it I'll just reproduce it again and send a new one from the new build.

Thanks!

**Comment by devgianlu** [comment] 2020-04-29 14:48
I've fixed the log output and made some other changes to hopefully fix this. I am having an hard time reproducing because my network is apparently too fast.

**Comment by Iscle** [comment] 2020-04-29 15:15
Tested it again. I have good news and bad new.

Good news is that the exception is not thrown anymore. (This means I couldn't test the log, but I will assume it's fixed now.)

Bad news is that now, when repeating the steps mentioned before, that caused the issue, the Spotify client shows the music as playing, but audio is not coming out. Also, pressing the "next song" button won't do anything. The request gets to librespot, as it's logged, but nothing happens. No changes in the UI nor audio output.

You can see what I mean with the next song button in the bottom of this log:
https://del.dog/upunufanun

I guess this issue is too much of an edge case, and doesn't really deserve our time right now... There might be more important things to do before this. 
It's just that some times, when discovering weekly, I do this (next song + seek to the middle of the song) quite frequently, and other people might do so too, so I think it was important to report, but maybe just to have it fixed when everything else is working fine.

**Comment by devgianlu** [comment] 2020-05-10 12:21
I am still trying to reproduce this, I've tried with this command which should be faster than any kind of user interaction:
```
curl -X POST http://localhost:24879/player/next && curl -X POST http://localhost:24879/player/seek?pos=30000
```

Still didn't cause the issue so I slowed down the loading by two seconds, no result either. 

@Iscle Can you test the command above (must run the API variant) to check if the problem is reproducible or it has to be done via the client?

**Closed** 2020-07-14 09:04 UTC
Labels: bug
