### ISSUE TITLE
Authentication fails with "PremiumAccountRequired" message

### ISSUE THREAD

**Issue by Standy131** [librespot-org/librespot-java#622] opened 2023-05-17 13:42 UTC
**Describe the bug**
I use librespot on raspberry Pi. Since 2 days ago I cannot connect. It was stable for last year or two.

I have duo account in Spotify (which is premium account).
Authentication method is set to USER_PASS.

**To Reproduce**
- Fresh installation of librespot
- Update auth method to USER_PASS, configure credentials

**Expected behavior**
Connection should be successful.

**Screenshots/Stracktraces/Logs**
```
root@ubuntu:/opt/spocon# tail -f /var/log/syslog
May 17 13:40:43 ubuntu systemd[1]: spocon.service: Failed with result 'exit-code'.
May 17 13:40:46 ubuntu kernel: [26543.237299] RTW: rtw_set_ps_mode(wlan1) Enter 802.11 power save - WIFI-TRAFFIC_IDLE
May 17 13:40:46 ubuntu kernel: [26543.237322] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): HW port id=0
May 17 13:40:46 ubuntu kernel: [26543.237339] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): fw ps mode = LPS, drv ps mode = 2, rlbm = 1 , smart_ps = 2, allQueueUAPSD = 0
May 17 13:40:48 ubuntu kernel: [26545.253227] RTW: rtw_set_ps_mode(wlan1) Leave 802.11 power save - WIFI-TRAFFIC_BUSY
May 17 13:40:48 ubuntu kernel: [26545.253249] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): HW port id=0
May 17 13:40:48 ubuntu kernel: [26545.253265] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): fw ps mode = ACTIVE, drv ps mode = 0, rlbm = 0 , smart_ps = 0, allQueueUAPSD = 0
May 17 13:40:50 ubuntu kernel: [26547.269055] RTW: rtw_set_ps_mode(wlan1) Enter 802.11 power save - WIFI-TRAFFIC_IDLE
May 17 13:40:50 ubuntu kernel: [26547.269084] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): HW port id=0
May 17 13:40:50 ubuntu kernel: [26547.269101] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): fw ps mode = LPS, drv ps mode = 2, rlbm = 1 , smart_ps = 2, allQueueUAPSD = 0
May 17 13:40:53 ubuntu systemd[1]: spocon.service: Scheduled restart job, restart counter is at 28.
May 17 13:40:53 ubuntu systemd[1]: Stopped SpoCon.
May 17 13:40:53 ubuntu systemd[1]: Starting SpoCon...
May 17 13:40:53 ubuntu kernel: [26549.704849] RTW: rtw_set_ps_mode(wlan1) Leave 802.11 power save - WIFI-LPS_CTRL_LEAVE
May 17 13:40:53 ubuntu kernel: [26549.704867] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): HW port id=0
May 17 13:40:53 ubuntu kernel: [26549.704878] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): fw ps mode = ACTIVE, drv ps mode = 0, rlbm = 0 , smart_ps = 0, allQueueUAPSD = 0
May 17 13:40:53 ubuntu sh[27483]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
May 17 13:40:53 ubuntu sh[27483]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=118 time=10.6 ms
May 17 13:40:53 ubuntu sh[27483]: --- spotify.com ping statistics ---
May 17 13:40:53 ubuntu sh[27483]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
May 17 13:40:53 ubuntu sh[27483]: rtt min/avg/max/mdev = 10.628/10.628/10.628/0.000 ms
May 17 13:40:53 ubuntu systemd[1]: Started SpoCon.
May 17 13:40:56 ubuntu kernel: [26553.316730] RTW: rtw_set_ps_mode(wlan1) Enter 802.11 power save - WIFI-TRAFFIC_IDLE
May 17 13:40:56 ubuntu kernel: [26553.316747] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): HW port id=0
May 17 13:40:56 ubuntu kernel: [26553.316756] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): fw ps mode = LPS, drv ps mode = 2, rlbm = 1 , smart_ps = 2, allQueueUAPSD = 0
May 17 13:40:58 ubuntu kernel: [26555.332617] RTW: rtw_set_ps_mode(wlan1) Leave 802.11 power save - WIFI-TRAFFIC_BUSY
May 17 13:40:58 ubuntu kernel: [26555.332642] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): HW port id=0
May 17 13:40:58 ubuntu kernel: [26555.332659] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): fw ps mode = ACTIVE, drv ps mode = 0, rlbm = 0 , smart_ps = 0, allQueueUAPSD = 0
May 17 13:40:59 ubuntu java[27484]: 2023-05-17 13:40:59,094 INFO  ApResolver:90 - Loaded aps into pool: {accesspoint=[ap-gew4.spotify.com:4070, ap-gew4.spotify.com:443, ap-gew4.spotify.com:80, ap-gew1.spotify.com:4070, ap-gue1.spotify.com:443, ap-guc3.spotify.com:80], dealer=[gew4-dealer.spotify.com:443, gew1-dealer.spotify.com:443, gue1-dealer.spotify.com:443, guc3-dealer.spotify.com:443], spclient=[gew4-spclient.spotify.com:443, gew1-spclient.spotify.com:443, gue1-spclient.spotify.com:443, guc3-spclient.spotify.com:443]}
May 17 13:40:59 ubuntu java[27484]: 2023-05-17 13:40:59,201 DEBUG TimeProvider:90 - Loaded time offset from NTP: -30ms
May 17 13:41:00 ubuntu java[27484]: 2023-05-17 13:41:00,987 INFO  Session:137 - Created new session! {deviceId: 7def1da197ea81b2875df91df020f9cc0aa41335, ap: ap-gew4.spotify.com:80, proxy: false}
May 17 13:41:01 ubuntu java[27484]: 2023-05-17 13:41:01,698 INFO  Session:331 - Connected successfully!
May 17 13:41:01 ubuntu java[27484]: 2023-05-17 13:41:01,924 ERROR Log4JUncaughtExceptionHandler:31 - [main]
May 17 13:41:01 ubuntu java[27484]: xyz.gianlu.librespot.core.Session$SpotifyAuthenticationException: PremiumAccountRequired
May 17 13:41:01 ubuntu java[27484]: #011at xyz.gianlu.librespot.core.Session.authenticatePartial(Session.java:450) ~[librespot-java-api-v1.6.2.jar:1.6.2]
May 17 13:41:01 ubuntu java[27484]: #011at xyz.gianlu.librespot.core.Session.authenticate(Session.java:339) ~[librespot-java-api-v1.6.2.jar:1.6.2]
May 17 13:41:01 ubuntu java[27484]: #011at xyz.gianlu.librespot.core.Session.access$600(Session.java:77) ~[librespot-java-api-v1.6.2.jar:1.6.2]
May 17 13:41:01 ubuntu java[27484]: #011at xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1029) ~[librespot-java-api-v1.6.2.jar:1.6.2]
May 17 13:41:01 ubuntu java[27484]: #011at xyz.gianlu.librespot.api.Main.withPlayer(Main.java:53) ~[librespot-java-api-v1.6.2.jar:1.6.2]
May 17 13:41:01 ubuntu java[27484]: #011at xyz.gianlu.librespot.api.Main.main(Main.java:45) ~[librespot-java-api-v1.6.2.jar:1.6.2]
May 17 13:41:02 ubuntu systemd[1]: spocon.service: Main process exited, code=exited, status=1/FAILURE
May 17 13:41:02 ubuntu systemd[1]: spocon.service: Failed with result 'exit-code'.
May 17 13:41:05 ubuntu kernel: [26561.380148] RTW: rtw_set_ps_mode(wlan1) Enter 802.11 power save - WIFI-TRAFFIC_IDLE
May 17 13:41:05 ubuntu kernel: [26561.380169] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): HW port id=0
May 17 13:41:05 ubuntu kernel: [26561.380187] RTW: rtl8822b_set_FwPwrMode_cmd(wlan1): fw ps mode = LPS, drv ps mode = 2, rlbm = 1 , smart_ps = 2, allQueueUAPSD = 0
```

**Version/Commit**
librespot-java-api-v1.6.2

**Comment by thedtvn** [comment] 2023-05-17 16:19
same

**Comment by devgianlu** [comment] 2023-05-17 16:30
Duplicate of https://github.com/librespot-org/librespot-java/issues/614, update to v1.6.3

**Closed as completed by devgianlu** 2023-05-17 16:30 UTC
Labels: bug
