### ISSUE TITLE
Exception in thread "main" com.electronwill.nightconfig.core.IncompatibleIntermediaryLevelException: Cannot get/create entry with parent path [cache] because of an incompatible intermediary value of type: class com.electronwill.nightconfig.core.SimpleCommentedConfig

### ISSUE THREAD

**Issue by ktzouno** [librespot-org/librespot-java#1028] opened 2024-11-29 19:28 UTC
**Describe the bug**

`java -jar librespot-player-1.6.4.jar` starts the first time properly and creates a `config.toml` file. But restarting it after that throws this exception:
```
Exception in thread "main" com.electronwill.nightconfig.core.IncompatibleIntermediaryLevelException: Cannot get/create entry with parent path [cache] because of an incompatible intermediary value of type: class com.electronwill.nightconfig.core.SimpleCommentedConfig
	at com.electronwill.nightconfig.core.concurrent.StampedConfig.getOrCreateConfig(StampedConfig.java:429)
	at com.electronwill.nightconfig.core.concurrent.StampedConfig.set(StampedConfig.java:576)
	at com.electronwill.nightconfig.core.utils.ConfigWrapper.set(ConfigWrapper.java:25)
	at com.electronwill.nightconfig.core.Config.set(Config.java:26)
2024-11-29 19:18:49,601 TRACE FileConfiguration:148 - Added new entry to configuration file: cache.dir
	at xyz.gianlu.librespot.player.FileConfiguration.checkMissingKeys(FileConfiguration.java:149)
	at xyz.gianlu.librespot.player.FileConfiguration.checkMissingKeys(FileConfiguration.java:144)
	at xyz.gianlu.librespot.player.FileConfiguration.updateConfigFile(FileConfiguration.java:196)
	at xyz.gianlu.librespot.player.FileConfiguration.<init>(FileConfiguration.java:95)
	at xyz.gianlu.librespot.player.Main.main(Main.java:36)
```

The `cache.dir` path it refers to in `config.toml` exists, because it was created by it in the first run:
```
### Cache ###
[cache]
        dir = "./cache/"
        # Cache enabled
        enabled = true
        doCleanUp = true
```

**Version/Commit**
`librespot-player-1.6.4.jar`

Any ideas? 🙂

**Comment by chommik** [comment] 2024-12-30 00:39
Looks like a duplicate of #1011.

**Closed as not planned** 2024-12-30 13:29 UTC
Labels: bug
