### ISSUE TITLE
How to improve performance on Raspberry Pi

### ISSUE THREAD

**Issue by tjibbevanderlaan** [librespot-org/librespot-java#162] opened 2019-12-23 17:55 UTC
First of all, thanks for this great piece of work, I am really enjoying it!

The software runs flawlessly on my MacBook Pro, but on my Raspberry Pi (Model B Plus Rev 1.2) the performance is worse. Files are not cached in time, which results in a lot of hick-ups during playback. Using another JVM (`oracle-java8-jre` instead of `openjdk-8-jdk`) seemed to improve the performance a bit, but not significantly enough.

Any ideas how I could improve the JVM performance? And do you expect that this repo will be optimised for raspbian in the future? Thanks!

**Comment by devgianlu** [comment] 2019-12-23 18:13
Consider using OpenJDK 9 which seems to run faster. (https://stackoverflow.com/questions/31153584/why-is-there-such-a-performance-difference-on-raspberry-pi-between-open-and-orac)

I don't know how much performance can still be gained, but I'll work on it. Can you provide a log file?

**Comment by lkwg82** [comment] 2019-12-23 19:27
mhm, better to use a maintained version: 11 or latest 13 (depends if 13 is supported by the lib)

But did u have profiled it a bit? visualvm should be sufficient.

**Comment by devgianlu** [comment] 2019-12-23 19:35
@lkwg82 I've profiled a lot using YourKit, the great part of the CPU usage is from the Vorbis decoder which I am not able to optimize. 

I did not quite understand from @tjibbevanderlaan if this is an issue with the playback or the preloading, the logs will tell. From there I can start having a deeper look at what's happening.

**Comment by tjibbevanderlaan** [comment] 2019-12-23 20:23
I have also tried OpenJDK 11 today. The performance seemed to be a lot better compared to OpenJDK 8 -- and even comparable with the performance on MacOS. However, the performance is not consistent.  

Sometimes playback is without hick-ups and sometimes it isn't. I've tried to identify what makes the difference (running service as a systemctl daemon versus directly from the command line), but could not find a pattern. 

When I tried to save the logs an hour ago, everything worked perfectly, but after a reboot the 'worse performance' appeared again.

In this case it took quite some time before a connection was established, and as soon the song start playing, the song stopped after several seconds -- this behaviour of starting and stopping remained all the time. You can find the [log files here](https://github.com/librespot-org/librespot-java/files/3996171/logs.txt).

**Comment by tjibbevanderlaan** [comment] 2019-12-23 20:26
And thanks for the quick response and suggestions!

> I've also read that you could
> 
> Use the HardFloat version of Raspbian instead of the SoftFloat. HF has much faster floating point operations - however SF is required for running Java. So it's either Java or performance, like normal.

I'm using the HardFloat version of Raspbian.

**Comment by tjibbevanderlaan** [comment] 2019-12-23 22:03
I'm running my Raspberry Pi headless, but managed to set-up a remote connection with VisualVM. 

<img width="992" alt="Screenshot 2019-12-23 at 22 31 58" src="https://user-images.githubusercontent.com/9050818/71381955-2a3b9b80-25d6-11ea-8fd6-20124552119b.png">

CPU usage is very high. When I profile the service on MacOS, CPU usage is around 0.7% on average. Please let me know if you are interested in a specific report.

**Comment by devgianlu** [comment] 2019-12-24 09:22
The logs seem "fine", but it's clear that something is slowing down the application a lot. The CPU never seems to throttle therefore it should pause like you noticed. 

To investigate further try running `top` (CPU usage) along with `iotop` or `iostat` to monitory disk usage. I'd also hook the YourKit profiler (I can give you a license key) to capture a performance snapshot that I can inspect.

**Comment by tjibbevanderlaan** [comment] 2019-12-24 12:05
Thanks for the tip. I could not find an indicator which explains its bad performance. 

Could you send me a temporary license key to make use of the YourKit profiler?

```
top - 11:33:43 up 32 min,  2 users,  load average: 3.34, 3.74, 3.02
Tasks:  75 total,   1 running,  46 sleeping,   0 stopped,   0 zombie
%Cpu(s): 44.7 us, 51.6 sy,  0.0 ni,  1.8 id,  0.1 wa,  0.0 hi,  1.8 si,  0.0 st
KiB Mem :   443084 total,   115360 free,   114652 used,   213072 buff/cache
KiB Swap:   102396 total,   102396 free,        0 used.   274112 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+         COMMAND                                                                                                                                  
22676 pi        20   0  210136  91968  11644 S 23.7 20.8   7:03.92 java                                                                                                                                     
12897 pi        20   0    8116   3256   2748 R 13.2  0.7   0:00.12 top                                                                                                                                      
  243 root      20   0    5080   2924   2676 S  2.6  0.7   1:50.06 bash                                                                                                                                     
    1 root      20   0    9644   5960   4800 S  0.0  1.3   0:07.37 systemd                                                                                                                                  
    2 root      20   0       0      0      0 S  0.0  0.0   0:00.01 kthreadd                                                                                                                                 
    6 root       0 -20       0      0      0 I  0.0  0.0   0:00.00 mm_percpu_wq                                                                                                                             
    7 root      20   0       0      0      0 S  0.0  0.0   0:22.30 ksoftirqd/0       
...
```

```
iostat
Linux 4.19.66+ (Marantz) 	24/12/19 	_armv6l_	(1 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          44.96    0.00   53.22    0.05    0.00    1.77

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
mmcblk0           4.66        95.34        41.99     189418      83422
```

```
iostat -x
Linux 4.19.66+ (Marantz) 	24/12/19 	_armv6l_	(1 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          34.93    0.00   62.00    0.10    0.00    2.97

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
mmcblk0           3.09     1.46    6.84    1.12   167.32    43.66    53.04     0.02    8.54    2.75   44.04   2.21   1.76
```

I've performed also a read/write test to verify performance of SD-card. This is good:
```
Read: 524288000 bytes (524 MB, 500 MiB) copied, 23.1619 s, 22.6 MB/s
Write: 524288000 bytes (524 MB, 500 MiB) copied, 28.1128 s, 18.6 MB/s
```

**Comment by devgianlu** [comment] 2019-12-24 12:23
> Could you send me a temporary license key to make use of the YourKit profiler?

How can I send it privately?

**Comment by tjibbevanderlaan** [comment] 2019-12-24 12:40
I've updated my Github-profile. Here you can find my email address:
https://github.com/tjibbevanderlaan

**Comment by tjibbevanderlaan** [comment] 2019-12-24 17:08
I couldn't get the YourKit profiler up and running. 

I found out that my -- rather old -- Raspberry Pi (Model B Plus Rev 1.2) has a ARM1176 processor which makes use of the ARMv6 processor architecture. This architecture seems not supported by the YourKit profiler toolkit:
- [Linux (x86/x64, ARMv5/ARMv7/AArch64, ppc/ppc64/ppc64le)](https://www.yourkit.com/java/profiler/features/)
- https://www.yourkit.com/forum/viewtopic.php?f=3&t=41026

I am not sure if the differences between ARMv7 and ARMv6 seems are crucial for performance (http://single-boards.com/armv6-vs-armv7/). Unfortunately, I do not have a Raspberry Pi 2 laying around to verify this.

**Comment by devgianlu** [comment] 2019-12-24 17:41
That's a bummer. You can send me a Visual VM dump then of the issue appearing.

**Comment by tjibbevanderlaan** [comment] 2019-12-24 19:21
Not sure if I can use Visual VM to create a dump remotely.. Nevertheless - I used `jmap` to create a dump:
https://drive.google.com/open?id=1UCY0v5PiDIfmQwZKXR0UfOdHbjj9Zi0q

**Comment by devgianlu** [comment] 2019-12-25 09:08
Unluckily the HPROF format provides a snapshot therefore a single moment in time: I am not able to tell what is eating through the CPU or causing the music to stop.

**Comment by tjibbevanderlaan** [comment] 2019-12-25 12:23
Hmm. Fortunately the forum of YourKit provided me a link to an older version of the YourKit profiler :) I will try to set-up this profiler later this week. Happy holidays!

**Comment by tjibbevanderlaan** [comment] 2020-01-11 12:50
Hmm, I've tried every version of the YourKit profiler. None of the (older) versions seems compatible for this board. 
```
model name	: ARMv6-compatible processor rev 7 (v6l)
Features	: half thumb fastmult vfp edsp java tls 
```
Log files: https://gist.github.com/tjibbevanderlaan/999e00cfd8cde39b56b0b9ec39b99031
Forum link: https://www.yourkit.com/forum/viewtopic.php?f=3&t=41026

Do you know a good source which explains how to create a heap / CPU usage dump over time remotely?

**Comment by devgianlu** [comment] 2020-01-11 17:49
The only way I know of is to sample using VisualVM. If you could create a sample of the entire issue, it would be great.

**Comment by devgianlu** [comment] 2020-03-01 10:45
I started thinking that maybe the best solution is to delegate a native library to do the decoding. While looking around I found this: https://github.com/vincentjames501/libvorbis-libogg-android

**Comment by devgianlu** [comment] 2020-03-01 16:55
@tjibbevanderlaan I have made some improvements to the performance of librespot-java. Could you maybe check them out?

**Comment by lkwg82** [comment] 2020-03-01 20:58
Where did u make it?

**Comment by devgianlu** [comment] 2020-03-01 21:12
> Where did u make it? Any branch?

On branch `dev`

**Comment by tjibbevanderlaan** [comment] 2020-03-02 20:21
Hi @devgianlu, thanks for developing these improvements! 

I tested the development build tonight and the improvements are substantial. When caching is enabled, playback stops approximately once a minute (instead of about every 5 - 10 seconds which was the case for the release branch). With caching disabled, I had no hiccups so far!

I will continue testing this week and will post my findings here.

**Comment by devgianlu** [comment] 2020-03-06 15:31
I started working on #179 to hopefully reduce the CPU and disk usage caused by the current cache implementation that uses an H2 database.

**Comment by tjibbevanderlaan** [comment] 2020-03-08 16:36
This week I used the `dev`-branch-build frequently (with cache-disabled), and playback is very good. Still no hiccups, so that's fantastic. 

Today I've checked out the `new cache`-branch as well, to verify how that performs. I'm playing now for a few hours with caching enabled and did not experienced a single hiccup so far :)

**Comment by devgianlu** [comment] 2020-03-08 16:56
That's great, I've merged the cache branch and I'll probably publish a new release in the next couple days if everything is stable.

**Closed** 2020-03-17 18:30 UTC
