### ISSUE TITLE
UnknownHostException / Failed reconnecting

### ISSUE THREAD

**Issue by paulbastian** [librespot-org/librespot-java#375] opened 2021-06-30 17:39 UTC
**Describe the bug**
librespot-java is not able to play music, this happens after some time(mostly days) of idle, if I restart the service, it always works again.

**To Reproduce**
Its not easy to reproduce, but consistly keeps happening after some amount of days.

**Expected behavior**
This bug started to happen like 1-2 months ago. It has never happened before that.

**Screenshots/Stracktraces/Logs**
```
Jun 30 19:24:55 soundpi2 java[12231]: 2021-06-30 19:24:55,843 TRACE DealerClient:271 - Scheduled reconnection attempt in 10 seconds...
Jun 30 19:24:55 soundpi2 java[12231]:         at java.lang.Thread.run(Thread.java:832) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$connectionInvalided$3(DealerClient.java:276) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.dealer.DealerClient.connect(DealerClient.java:79) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.TokenProvider.get(TokenProvider.java:79) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.TokenProvider.getToken(TokenProvider.java:68) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:104) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:89) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.mercury.MercuryClient.send(MercuryClient.java:174) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session.send(Session.java:559) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session.sendUnchecked(Session.java:518) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]: java.io.IOException: Cannot write to missing connection.
Jun 30 19:24:55 soundpi2 java[12231]: 2021-06-30 19:24:55,842 ERROR DealerClient:278 - Failed reconnecting, retrying...
Jun 30 19:24:55 soundpi2 java[12231]: 2021-06-30 19:24:55,842 TRACE MercuryClient:156 - Send Mercury request, seq: 55939, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea9>
Jun 30 19:24:55 soundpi2 java[12231]: 2021-06-30 19:24:55,842 DEBUG TokenProvider:67 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
Jun 30 19:24:55 soundpi2 java[12231]:         at java.lang.Thread.run(Thread.java:832) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session.reconnect(Session.java:712) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session$ConnectionHolder.create(Session.java:1242) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.net.Socket.<init>(Socket.java:294) ~[?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.net.Socket.<init>(Socket.java:520) ~[?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.net.Socket.connect(Socket.java:597) ~[?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.net.Socket.connect(Socket.java:648) ~[?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
Jun 30 19:24:55 soundpi2 java[12231]:         at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
Jun 30 19:24:55 soundpi2 java[12231]: java.net.UnknownHostException: guc3-accesspoint-d-h5gv.ap.spotify.com
Jun 30 19:24:55 soundpi2 java[12231]: 2021-06-30 19:24:55,305 ERROR Session:730 - Failed reconnecting, retrying in 10 seconds...
Jun 30 19:24:54 soundpi2 java[12231]:         at java.lang.Thread.run(Thread.java:832) [?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session.reconnect(Session.java:712) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:54 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session$ConnectionHolder.create(Session.java:1242) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.net.Socket.<init>(Socket.java:294) ~[?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.net.Socket.<init>(Socket.java:520) ~[?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.net.Socket.connect(Socket.java:597) ~[?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.net.Socket.connect(Socket.java:648) ~[?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
Jun 30 19:24:54 soundpi2 java[12231]:         at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
Jun 30 19:24:54 soundpi2 java[12231]: java.net.UnknownHostException: gew1-accesspoint-d-vscb.ap.spotify.com
Jun 30 19:24:54 soundpi2 java[12231]: 2021-06-30 19:24:54,871 ERROR Session:730 - Failed reconnecting, retrying in 10 seconds...
Jun 30 19:24:45 soundpi2 java[12231]: 2021-06-30 19:24:45,842 TRACE DealerClient:271 - Scheduled reconnection attempt in 10 seconds...
Jun 30 19:24:45 soundpi2 java[12231]:         at java.lang.Thread.run(Thread.java:832) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$connectionInvalided$3(DealerClient.java:276) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.dealer.DealerClient.connect(DealerClient.java:79) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.TokenProvider.get(TokenProvider.java:79) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.TokenProvider.getToken(TokenProvider.java:68) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:104) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:89) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.mercury.MercuryClient.send(MercuryClient.java:174) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session.send(Session.java:559) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session.sendUnchecked(Session.java:518) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]: java.io.IOException: Cannot write to missing connection.
Jun 30 19:24:45 soundpi2 java[12231]: 2021-06-30 19:24:45,841 ERROR DealerClient:278 - Failed reconnecting, retrying...
Jun 30 19:24:45 soundpi2 java[12231]: 2021-06-30 19:24:45,841 TRACE MercuryClient:156 - Send Mercury request, seq: 55938, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea9>
Jun 30 19:24:45 soundpi2 java[12231]: 2021-06-30 19:24:45,841 DEBUG TokenProvider:67 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
Jun 30 19:24:45 soundpi2 java[12231]:         at java.lang.Thread.run(Thread.java:832) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session.reconnect(Session.java:712) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at xyz.gianlu.librespot.core.Session$ConnectionHolder.create(Session.java:1242) ~[librespot-player.jar:1.6.0]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.net.Socket.<init>(Socket.java:294) ~[?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.net.Socket.<init>(Socket.java:520) ~[?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.net.Socket.connect(Socket.java:597) ~[?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.net.Socket.connect(Socket.java:648) ~[?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
Jun 30 19:24:45 soundpi2 java[12231]:         at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
Jun 30 19:24:45 soundpi2 java[12231]: java.net.UnknownHostException: gew1-accesspoint-d-mv1p.ap.spotify.com
```
and so on...

**Version/Commit**
Version used or commit pulled if compiled locally.
1.6.0

Thanks for having a look at this!

**Comment by devgianlu** [comment] 2021-06-30 17:41
Duplicate of https://github.com/spocon/spocon/issues/37 maybe?

**Closed as completed** 2021-07-04 14:49 UTC
Labels: bug
