### ISSUE TITLE
Sudden problems, Spotify not connecting

### ISSUE THREAD

**Issue by paulbastian** [librespot-org/librespot-java#278] opened 2020-12-16 21:26 UTC
**Describe the bug**
Since 3 days, my both setups plying librespot-java are not working any more, connection is not successful with spotify connect

**To Reproduce**
Problem happens always, 100% unsuccessful

**Screenshots/Stracktraces/Logs**
Log is reverse.
```
[user@pi ~]$ journalctl -r -u librespot-java
-- Logs begin at Sun 2020-08-09 00:29:01 CEST, end at Wed 2020-12-16 22:16:26 CET. --
Dec 16 22:14:44 pi4 java[300]: 2020-12-16 22:14:44,277 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 5, flags: 1, parts: 2
Dec 16 22:14:44 pi4 java[300]: 2020-12-16 22:14:44,187 TRACE MercuryClient:138 - Send Mercury request, seq: 5, uri: hm://context-resolve/v1/spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYV>
Dec 16 22:14:44 pi4 java[300]: 2020-12-16 22:14:44,186 DEBUG Player:354 - Loading context (transfer), uri: spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYVGvF9ch6wz
Dec 16 22:14:44 pi4 java[300]: 2020-12-16 22:14:44,179 DEBUG Player:282 - Received command: Transfer
Dec 16 22:14:44 pi4 java[300]: 2020-12-16 22:14:44,177 TRACE DealerClient:97 - Received request. {mid: hm://connect-state/v1/player/command, key: 0365ac55-8482-4fdd-bcd3-86086d31bf61, pid: 1835515831, sender: 9>
Dec 16 22:14:39 pi4 java[300]: ify:track:4uRW7Q5JdBNmpCMknCav6w" uid: "ee81de7e7b2ecf648a7d" metadata { key: "context_uri" value: "spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYVGvF9ch6wz>
Dec 16 22:14:39 pi4 java[300]: 2020-12-16 22:14:39,062 TRACE DeviceStateHandler:160 - Received cluster update at 1608153279006: cluster { timestamp: 1608153278522 active_device_id: "9b14b4d094c20423f8c5897fef98>
Dec 16 22:14:38 pi4 java[300]: 2020-12-16 22:14:38,946 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 4, flags: 1, parts: 2
Dec 16 22:14:38 pi4 java[300]: 2020-12-16 22:14:38,815 TRACE MercuryClient:138 - Send Mercury request, seq: 4, uri: hm://context-resolve/v1/spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYV>
Dec 16 22:14:38 pi4 java[300]: 2020-12-16 22:14:38,813 DEBUG DeviceStateHandler:198 - Device is now active. {ts: 1608153278810}
Dec 16 22:14:38 pi4 java[300]: 2020-12-16 22:14:38,807 DEBUG Player:354 - Loading context (transfer), uri: spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYVGvF9ch6wz
Dec 16 22:14:38 pi4 java[300]: 2020-12-16 22:14:38,798 DEBUG Player:282 - Received command: Transfer
Dec 16 22:14:38 pi4 java[300]: 2020-12-16 22:14:38,795 TRACE DealerClient:97 - Received request. {mid: hm://connect-state/v1/player/command, key: c7b58163-9862-45d7-98ea-48f3bb87c0d6, pid: 1835510549, sender: 9>
Dec 16 22:14:32 pi4 java[300]: ify:track:4uRW7Q5JdBNmpCMknCav6w" uid: "ee81de7e7b2ecf648a7d" metadata { key: "context_uri" value: "spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYVGvF9ch6wz>
Dec 16 22:14:32 pi4 java[300]: 2020-12-16 22:14:32,993 TRACE DeviceStateHandler:160 - Received cluster update at 1608153272940: cluster { timestamp: 1608153272532 active_device_id: "9b14b4d094c20423f8c5897fef98>
Dec 16 22:14:25 pi4 java[300]: ify:track:4uRW7Q5JdBNmpCMknCav6w" uid: "ee81de7e7b2ecf648a7d" metadata { key: "context_uri" value: "spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYVGvF9ch6wz>
Dec 16 22:14:25 pi4 java[300]: 2020-12-16 22:14:25,567 TRACE DeviceStateHandler:160 - Received cluster update at 1608153265506: cluster { timestamp: 1608153264919 active_device_id: "9b14b4d094c20423f8c5897fef98>
Dec 16 22:14:25 pi4 java[300]: ify:track:4uRW7Q5JdBNmpCMknCav6w" uid: "ee81de7e7b2ecf648a7d" metadata { key: "context_uri" value: "spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYVGvF9ch6wz>
Dec 16 22:14:25 pi4 java[300]: 2020-12-16 22:14:25,422 TRACE DeviceStateHandler:160 - Received cluster update at 1608153265311: cluster { timestamp: 1608153264912 active_device_id: "9b14b4d094c20423f8c5897fef98>
Dec 16 22:13:38 pi4 java[300]: 2020-12-16 22:13:38,603 INFO  DeviceStateHandler:249 - Put state. {ts: 1608153218503, connId: OGQ5M...yMURF, reason: BECAME_INACTIVE, request: device { device_info { can_play: tru>
Dec 16 22:13:38 pi4 java[300]: 2020-12-16 22:13:38,507 INFO  StateWrapper:320 - Notified inactivity!
Dec 16 22:13:38 pi4 java[300]: y:track:4uRW7Q5JdBNmpCMknCav6w" uid: "ee81de7e7b2ecf648a7d" metadata { key: "context_uri" value: "spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYVGvF9ch6wz" >
Dec 16 22:13:38 pi4 java[300]: 2020-12-16 22:13:38,504 TRACE DeviceStateHandler:160 - Received cluster update at 1608153218390: cluster { timestamp: 1608153217839 active_device_id: "9b14b4d094c20423f8c5897fef98>
Dec 16 22:12:20 pi4 java[300]: 2020-12-16 22:12:20,187 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 3, flags: 1, parts: 2
Dec 16 22:12:20 pi4 java[300]: 2020-12-16 22:12:20,027 TRACE MercuryClient:138 - Send Mercury request, seq: 3, uri: hm://context-resolve/v1/spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYV>
Dec 16 22:12:20 pi4 java[300]: 2020-12-16 22:12:20,023 DEBUG DeviceStateHandler:198 - Device is now active. {ts: 1608153140020}
Dec 16 22:12:20 pi4 java[300]: 2020-12-16 22:12:20,005 DEBUG Player:354 - Loading context (transfer), uri: spotify:user:wamvxztrfpcomxphv6401as55:collection:artist:6XyY86QOPPrYVGvF9ch6wz
Dec 16 22:12:19 pi4 java[300]: 2020-12-16 22:12:19,863 DEBUG Player:282 - Received command: Transfer
Dec 16 22:12:19 pi4 java[300]: 2020-12-16 22:12:19,849 TRACE DealerClient:97 - Received request. {mid: hm://connect-state/v1/player/command, key: fb51b425-d5fc-4193-957f-c44a65d24ac6, pid: 1835371503, sender: 9>
Dec 16 22:12:19 pi4 java[300]: 2020-12-16 22:12:19,070 INFO  DeviceStateHandler:249 - Put state. {ts: 1608153138655, connId: OGQ5M...yMURF, reason: NEW_DEVICE, request: device { device_info { can_play: true vol>
Dec 16 22:12:18 pi4 java[300]: 2020-12-16 22:12:18,665 INFO  StateWrapper:300 - Notified new device (us)!
Dec 16 22:12:18 pi4 java[300]: 2020-12-16 22:12:18,641 DEBUG DeviceStateHandler:135 - Updated Spotify-Connection-Id: OGQ5MzdlODhjYzc5YWRjNTAxYmJjNGExMDRiOWEyYjA4NzUxNDM1OCtkZWFsZXIrdGNwOi8vZ2FlMi1kZWFsZXItYi12N>
Dec 16 22:12:18 pi4 java[300]: 2020-12-16 22:12:18,631 DEBUG DealerClient:324 - Dealer connected! {host: gae-dealer.spotify.com}
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,794 TRACE AsyncProcessor:36 - AsyncProcessor{put-state-worker} has started
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,493 INFO  Session:344 - Authenticated as wamvxztrfpcomxphv6401as55!
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,492 INFO  CacheManager:80 - There are 112 cached entries.
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,449 DEBUG TokenProvider:55 - Updated token successfully! {scopes: [playlist-read], newToken: StoredToken{expiresIn=3600, accessToken='BQAlQr...X3QlXA', scopes=>
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,443 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 2
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,382 DEBUG EventService:35 - Event sent. {body: 812|1|en, result: 200}
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,380 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 2, flags: 1, parts: 1
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,322 DEBUG MercuryClient:216 - Couldn't dispatch Mercury event {seq: -4448917615586312192, uri: hm://pusher/v1/connections/OGQ5MzdlODhjYzc5YWRjNTAxYmJjNGExMDRiO>
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,316 TRACE MercuryClient:181 - Handling packet, cmd: MercuryEvent, seq: -4448917615586312192, flags: 1, parts: 1
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,313 INFO  Session:1302 - Skipping unknown command {cmd: 0x75, payload: 000000}
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,301 DEBUG Session:1351 - Received 0x10: 1492289F922E018E4712CBE2238F268651BB9B44
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,300 INFO  Session:1375 - Skipping UnknownData_AllZeros
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,299 INFO  Session:1375 - Skipping LegacyWelcome
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,299 TRACE Session:732 - Parsed product info: {remote-control=6, audio-preview-url-template=https://p.scdn.co/mp3-preview/{id}, incognito_mode_timeout=21600, ad>
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,295 TRACE MercuryClient:138 - Send Mercury request, seq: 2, uri: hm://event-service/v1/events, method: POST
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,290 TRACE MercuryClient:138 - Send Mercury request, seq: 1, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca8>
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,266 DEBUG TokenProvider:51 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,259 INFO  Session:1337 - Received CountryCode: DE
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,258 INFO  Session:1347 - Received LicenseVersion: 0
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,256 INFO  Session:1375 - Skipping SecretBlock
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,254 TRACE AsyncProcessor:36 - AsyncProcessor{event-service-sender} has started
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,247 TRACE AsyncProcessor:36 - AsyncProcessor{dealer-worker} has started
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,215 TRACE AsyncProcessor:36 - AsyncProcessor{pm-channels} has started
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,213 TRACE AsyncProcessor:36 - AsyncProcessor{pm-audio-keys} has started
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,208 TRACE AsyncProcessor:36 - AsyncProcessor{pm-mercury} has started
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,195 TRACE Session:1293 - Session.Receiver started
Dec 16 22:12:17 pi4 java[300]: 2020-12-16 22:12:17,057 INFO  Session:313 - Connected successfully!
Dec 16 22:12:16 pi4 java[300]: 2020-12-16 22:12:16,471 INFO  Session:122 - Created new session! {deviceId: 8d937e88cc79adc501bbc4a104b9a2b087514358, ap: gew1-accesspoint-b-mh82.ap.spotify.com:4070, proxy: false}
Dec 16 22:12:15 pi4 java[300]: 2020-12-16 22:12:15,529 DEBUG TimeProvider:74 - Loaded time offset from NTP: -2ms
Dec 16 22:12:15 pi4 java[300]: 2020-12-16 22:12:15,472 INFO  ApResolver:68 - Loaded aps into pool: {accesspoint=[gew1-accesspoint-b-mh82.ap.spotify.com:4070, gew1-accesspoint-b-0rtr.ap.spotify.com:443, gew1-acc>
Dec 16 22:12:15 pi4 java[300]: 2020-12-16 22:12:15,208 INFO  ZeroconfServer:329 - Accepted new user from Galaxy S9+ von Paul. {deviceId: 8d937e88cc79adc501bbc4a104b9a2b087514358}
Dec 16 22:12:14 pi4 java[300]: 2020-12-16 22:12:14,934 TRACE ZeroconfServer:520 - Handling request: POST / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.88 Android/29 (SM-G965F>
Dec 16 22:12:14 pi4 java[300]: 2020-12-16 22:12:14,799 TRACE ZeroconfServer:520 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify>
Dec 16 22:12:12 pi4 java[300]: 2020-12-16 22:12:12,129 TRACE ZeroconfServer:520 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify>
Dec 16 22:12:10 pi4 java[300]: 2020-12-16 22:12:10,373 TRACE ZeroconfServer:520 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify>
Dec 16 22:10:27 pi4 java[300]: 2020-12-16 22:10:27,767 TRACE ZeroconfServer:520 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify>
Dec 16 22:10:20 pi4 java[300]: 2020-12-16 22:10:20,035 TRACE ZeroconfServer:520 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify>
Dec 16 22:10:17 pi4 java[300]: 2020-12-16 22:10:17,327 TRACE ZeroconfServer:520 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.88 Androi>
Dec 16 22:01:55 pi4 java[300]: 2020-12-16 22:01:55,022 INFO  Zeroconf:473 - Announced Service{alias='Technics_Boxen_AUX2', service='spotify-connect', port=59513, text={VERSION=1.0, CPath=/, Stack=SP}, addresses>
Dec 16 22:01:53 pi4 java[300]: 2020-12-16 22:01:53,496 INFO  ZeroconfServer:456 - Zeroconf HTTP server started successfully on port 59513!
Dec 16 22:01:53 pi4 java[300]: 2020-12-16 22:01:53,315 INFO  Utils:84 - Cryptography restrictions removal not needed.
Dec 16 22:01:49 pi4 systemd[1]: Started A spotify playing daemon.
```

**Version/Commit**
I have recent compiled version in pi#1 and 1.52 release on pi#2
Any ideas what suddenly might have happened?

**Comment by devgianlu** [comment] 2020-12-16 21:36
Duplicate of #277. No idea what's happening.

**Closed** 2020-12-16 21:36 UTC
Labels: bug, duplicate
