### ISSUE TITLE
NPE receiving SkipPrev

### ISSUE THREAD

**Issue by leafy7382** [librespot-org/librespot-java#136] opened 2019-09-16 15:43 UTC
NPE when trying to skip to a previous track on a single track replay (this is the result of a search)

restrictions { disallow_resuming_reasons: "not_paused" disallow_skipping_prev_reasons: "no_prev_track" } suppressions { } context_metadata { key: "track_count" value: "1" } } }

Branch: spotify-new-api (was trying to test fix for #135)

[info.log](https://github.com/librespot-org/librespot-java/files/3617042/info.log)

**Comment by devgianlu** [comment] 2019-09-16 17:57
This was caused by pressing previous after 3000ms from the start of the song making the player seek while the content was still loading. Should be fixed.

**Closed** 2019-09-16 19:28 UTC
Labels: bug, new-spotify-api
