### ISSUE TITLE
Failed loading autoplay station!

### ISSUE THREAD

**Issue by Zageron** [librespot-org/librespot-java#284] opened 2021-01-01 01:20 UTC
**Describe the bug**
When spotify attempts to find the next song to play using autoplay it fails.

**To Reproduce**
Select a single song and play it.

**Expected behavior**
Skipping to next track when no queue is present should function.

**Screenshots/Stracktraces/Logs**
```zsh
Jan 01 01:18:41 spotipi java[6566]: 2021-01-01 01:18:41,944 DEBUG Player:293 - Received command: SkipNext
Jan 01 01:18:41 spotipi java[6566]: 2021-01-01 01:18:41,951 TRACE MercuryClient:140 - Send Mercury request, seq: 8, uri: hm://autoplay-enabled/query?uri=spotify:user:zager0n:collection, method: GET
Jan 01 01:18:42 spotipi java[6566]: 2021-01-01 01:18:42,217 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 8, flags: 1, parts: 1
Jan 01 01:18:42 spotipi java[6566]: 2021-01-01 01:18:42,220 TRACE MercuryClient:140 - Send Mercury request, seq: 9, uri: hm://radio-apollo/v3/stations/spotify:user:zager0n:collection, method: GET
Jan 01 01:18:42 spotipi java[6566]: 2021-01-01 01:18:42,494 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 9, flags: 1, parts: 1
Jan 01 01:18:42 spotipi java[6566]: 2021-01-01 01:18:42,497 FATAL Player:543 - Failed loading autoplay station!
Jan 01 01:18:42 spotipi java[6566]: xyz.gianlu.librespot.mercury.MercuryClient$MercuryException: status: 400
Jan 01 01:18:42 spotipi java[6566]:         at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:90) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:18:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.Player.loadAutoplay(Player.java:527) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:18:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.Player.handleSkipNext(Player.java:461) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:18:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.Player.command(Player.java:312) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:18:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:18:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:18:42 spotipi java[6566]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:18:42 spotipi java[6566]:         at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:18:42 spotipi java[6566]:         at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:18:42 spotipi java[6566]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jan 01 01:18:42 spotipi java[6566]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Jan 01 01:18:42 spotipi java[6566]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Jan 01 01:18:42 spotipi java[6566]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Jan 01 01:18:42 spotipi java[6566]: 2021-01-01 01:18:42,538 DEBUG DealerClient:109 - Handled request. {key: b42df0d2-ac13-462a-8e92-b7ef65dd61fb, result: SUCCESS}
```

**Version/Commit**
Release 1.5.3

**Comment by Zageron** [comment] 2021-01-01 01:21
When in this state, without restarting the service, the following error occurs when attempting to play another song afterward.
```zsh
Jan 01 01:20:41 spotipi java[6566]: 2021-01-01 01:20:41,705 DEBUG Player:293 - Received command: Play
Jan 01 01:20:41 spotipi java[6566]: 2021-01-01 01:20:41,707 DEBUG Player:346 - Loading context (play), uri: spotify:user:zager0n:collection
Jan 01 01:20:41 spotipi java[6566]: 2021-01-01 01:20:41,734 TRACE MercuryClient:140 - Send Mercury request, seq: 10, uri: hm://context-resolve/v1/spotify:user:zager0n:collection, method: GET
Jan 01 01:20:42 spotipi java[6566]: 2021-01-01 01:20:42,040 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 10, flags: 0, parts: 1
Jan 01 01:20:42 spotipi java[6566]: 2021-01-01 01:20:42,045 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 10, flags: 2, parts: 1
Jan 01 01:20:42 spotipi java[6566]: 2021-01-01 01:20:42,047 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 10, flags: 2, parts: 1
Jan 01 01:20:42 spotipi java[6566]: 2021-01-01 01:20:42,049 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 10, flags: 1, parts: 1
Jan 01 01:20:42 spotipi java[6566]: 2021-01-01 01:20:42,209 TRACE StateWrapper:1084 - Initialized current track index to 545.
Jan 01 01:20:42 spotipi java[6566]: 2021-01-01 01:20:42,210 DEBUG Player:225 - Loading session, id: ULGE1S99F73+rfsW78R/qg, play: true
Jan 01 01:20:42 spotipi java[6566]: 2021-01-01 01:20:42,213 ERROR DealerClient:112 - Failed handling request. {key: e99c473c-7460-4c87-8b27-3a237c92bdc7}
Jan 01 01:20:42 spotipi java[6566]: java.lang.NullPointerException: null
Jan 01 01:20:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.Player.endMetrics(Player.java:566) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:20:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.Player.loadSession(Player.java:230) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:20:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.Player.handlePlay(Player.java:354) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:20:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.Player.command(Player.java:297) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:20:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:20:42 spotipi java[6566]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:20:42 spotipi java[6566]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:20:42 spotipi java[6566]:         at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:20:42 spotipi java[6566]:         at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:20:42 spotipi java[6566]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jan 01 01:20:42 spotipi java[6566]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Jan 01 01:20:42 spotipi java[6566]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Jan 01 01:20:42 spotipi java[6566]:         at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Zageron** [comment] 2021-01-01 01:22
Running `sudo systemctl restart spocon` resolves the issue as long as I always have a proper queue.

**Comment by devgianlu** [comment] 2021-01-01 09:22
@Zageron Should be fixed now. Please explain the "as long as I always have a proper queue" issue.

**Comment by Zageron** [comment] 2021-01-01 09:38
Thanks! I was just clarifying that the state of the service is broken until I restart it. It functions as expected until my queue runs out of songs and then the app breaks.

I'll grab the new build after a sleep and let you know if it repros.

**Comment by devgianlu** [comment] 2021-01-03 10:16
@Zageron Any update?

**Comment by Zageron** [comment] 2021-01-04 05:58
I currently don't have a way to build and replace the binary, and I haven't put the time in to doing so. I can test if you supply a jar or if an action was set up for a nightly or something.

**Comment by devgianlu** [comment] 2021-01-04 09:22
@Zageron Snapshots are always available: https://oss.sonatype.org/content/repositories/snapshots/xyz/gianlu/librespot/

**Comment by Zageron** [comment] 2021-01-04 17:12
> @Zageron Snapshots are always available: https://oss.sonatype.org/content/repositories/snapshots/xyz/gianlu/librespot/

Ah, my bad. Thank you.

**Comment by Zageron** [comment] 2021-01-04 20:02
```
Jan 04 20:01:54 spotipi java[4163]: 2021-01-04 20:01:54,081 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 75, flags: 1, parts: 1
Jan 04 20:01:54 spotipi java[4163]: 2021-01-04 20:01:54,082 DEBUG EventService:35 - Event sent. {body: 10|20|d422ce55d1688e277e9a71e8f9444054b50d515a|019c9e75f5b5473d5ee39a6466b1011c|0|0|0|0|0|0|2208348|4436572|music|-1|-1|-1|-1.000000|-1|-1.000000|-1|-1|-1|-1.000000|-1|-1|-1|-1|-1.000000|-1|0.000000|-1.000000|||unknown|0|0|0|0|0|interactive|0|176400|0|0, result: 200}
Jan 04 20:01:54 spotipi java[4163]: 2021-01-04 20:01:54,083 TRACE MercuryClient:140 - Send Mercury request, seq: 77, uri: hm://event-service/v1/events, method: POST
Jan 04 20:01:54 spotipi java[4163]: 2021-01-04 20:01:54,139 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 76, flags: 1, parts: 1
Jan 04 20:01:54 spotipi java[4163]: 2021-01-04 20:01:54,140 FATAL Player:542 - Failed loading autoplay station!
Jan 04 20:01:54 spotipi java[4163]: xyz.gianlu.librespot.mercury.MercuryClient$MercuryException: status: 404
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:90) ~[librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.player.PagesLoader.getPage(PagesLoader.java:95) ~[librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.player.PagesLoader.nextPage(PagesLoader.java:129) ~[librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.initializeStart(StateWrapper.java:1049) ~[librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.player.StateWrapper.loadContext(StateWrapper.java:459) ~[librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.player.Player.loadAutoplay(Player.java:511) [librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.player.Player.nextPlayable(Player.java:752) [librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.player.playback.PlayerSession.advance(PlayerSession.java:111) [librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.player.playback.PlayerSession.playbackEnded(PlayerSession.java:141) [librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:324) [librespot-api-1.5.4-20210101.142549-1.jar:1.5.4-SNAPSHOT]
Jan 04 20:01:54 spotipi java[4163]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Jan 04 20:01:54 spotipi java[4163]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Jan 04 20:01:54 spotipi java[4163]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Jan 04 20:01:54 spotipi java[4163]: 2021-01-04 20:01:54,170 TRACE PlayerQueueEntry:325 - PlayerQueueEntry{019c9e75f5b5473d5ee39a6466b1011c} terminated.
Jan 04 20:01:54 spotipi java[4163]: 2021-01-04 20:01:54,184 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 77, flags: 1, parts: 1
Jan 04 20:01:54 spotipi java[4163]: 2021-01-04 20:01:54,185 DEBUG EventService:35 - Event sent. {body: 372|1|019c9e75f5b5473d5ee39a6466b1011c|spotify:track:4V4M8qghcdPWeGi1GKDo44|0|[[0,110964],[110964,113536]], result: 200}
```

**Comment by devgianlu** [comment] 2021-01-04 21:43
This is correct behavior. Not all contexts can be "autoplayed". Is the client still responsive after this? Are you able to play something else?

**Comment by Zageron** [comment] 2021-01-04 22:04
Yes.

**Comment by devgianlu** [comment] 2021-01-04 22:32
This is the intended behavior. Closing.

**Closed by devgianlu** 2021-01-04 22:32 UTC
Labels: bug
