### ISSUE TITLE
zeroconf not working (possible duplicate)

### ISSUE THREAD

**Issue by elganzua124** [librespot-org/librespot-java#80] opened 2019-04-14 23:50 UTC
Hi, now the program works great,  I just spent all day listening to music and podcasts without any problem and without needing to restart, that's pretty good. I thank you, now that I see that the program is more robust and stable  I would like to present librespot-java to the rest of the family, but I find it difficult to make it work with the zeroconf mode. Once the program had started, the device is visible from any client in the same network, but when anyone tries to connect, it tries a few seconds without success, after that the program hangs and no longer appears in the list of available devices. Here is the log:

**UPDATE: It only happens on my raspberry, if I run librespot-java on my pc desktop zeroconf mode works.**
```
-- Logs begin at Thu 2016-11-03 17:16:42 GMT, end at Sun 2019-04-14 14:41:35 BST. --
Apr 14 13:39:45 raspberrypi systemd[1]: Starting SpotiPi...
Apr 14 13:39:46 raspberrypi sh[497]: PING google.com (216.58.202.46) 56(84) bytes of data.
Apr 14 13:39:46 raspberrypi sh[497]: 64 bytes from eze04s05-in-f14.1e100.net (216.58.202.46): icmp_seq=1 ttl=56 time=5.91 ms
Apr 14 13:39:46 raspberrypi sh[497]: --- google.com ping statistics ---
Apr 14 13:39:46 raspberrypi sh[497]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Apr 14 13:39:46 raspberrypi sh[497]: rtt min/avg/max/mdev = 5.917/5.917/5.917/0.000 ms
Apr 14 13:39:46 raspberrypi systemd[1]: Started SpotiPi.
Apr 14 13:39:48 raspberrypi java[512]: 2019-04-14 13:39:48 INFO  Utils:139 - Successfully removed cryptography restrictions.
Apr 14 13:39:48 raspberrypi java[512]: 2019-04-14 13:39:48 INFO  ZeroconfServer:318 - Zeroconf HTTP server started successfully on port 55321!
Apr 14 13:39:48 raspberrypi java[512]: 2019-04-14 13:39:48 TRACE ZeroconfServer:165 - Adding addresses of wlan0 (displayName: wlan0)
Apr 14 13:39:48 raspberrypi java[512]: 2019-04-14 13:39:48 DEBUG ZeroconfServer:107 - Registering service on [/fe80:0:0:0:9027:30ee:658c:3d02%wlan0, /192.168.100.18]
Apr 14 13:39:48 raspberrypi java[512]: 2019-04-14 13:39:48 INFO  ZeroconfServer:120 - SpotifyConnect service registered successfully!
Apr 14 14:34:28 raspberrypi java[512]: 2019-04-14 14:34:28 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:31 raspberrypi java[512]: 2019-04-14 14:34:31 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:32 raspberrypi java[512]: 2019-04-14 14:34:32 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:34 raspberrypi java[512]: 2019-04-14 14:34:34 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:36 raspberrypi java[512]: 2019-04-14 14:34:36 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:44 raspberrypi java[512]: 2019-04-14 14:34:44 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:45 raspberrypi java[512]: 2019-04-14 14:34:45 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:47 raspberrypi java[512]: 2019-04-14 14:34:47 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:49 raspberrypi java[512]: 2019-04-14 14:34:49 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:51 raspberrypi java[512]: 2019-04-14 14:34:51 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:53 raspberrypi java[512]: 2019-04-14 14:34:53 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:55 raspberrypi java[512]: 2019-04-14 14:34:55 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:57 raspberrypi java[512]: 2019-04-14 14:34:57 TRACE ZeroconfServer:354 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:34:59 raspberrypi java[512]: 2019-04-14 14:34:59 TRACE ZeroconfServer:354 - Handling request: POST / HTTP/1.1, headers: {Keep-Alive=0, User-Agent=Spotify/110400197 Win32/0 (PC laptop), Connection=keep-alive, Host=192.168.100.18, Accept-Encoding=gzip, Content-Length=672, Content-Type=application/x-www-form-urlencoded}
Apr 14 14:35:01 raspberrypi java[512]: 2019-04-14 14:35:01 INFO  Session:97 - Created new session! {deviceId: 7dba87b4-2188-42ee-9a52-0bdabc9f6b8c, ap: guc3-accesspoint-b-938b.ap.spotify.com/104.154.126.170}
Apr 14 14:35:01 raspberrypi java[512]: 2019-04-14 14:35:01 INFO  ZeroconfServer:278 - Accepted new user. {deviceId: 7dba87b4-2188-42ee-9a52-0bdabc9f6b8c}
Apr 14 14:35:03 raspberrypi java[512]: 2019-04-14 14:35:03 INFO  Session:241 - Connected successfully!
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 DEBUG TimeProvider:20 - Corrected time offset, delta: -1s
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 TRACE Session:725 - Handled Ping {payload: 5CB33707}
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 INFO  Session:762 - Skipping SecretBlock
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 INFO  Session:742 - Received LicenseVersion: 1, 1.0.0-AR
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 INFO  Session:735 - Received CountryCode: AR
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 INFO  Session:762 - Skipping ProductInfo
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 INFO  Session:762 - Skipping LegacyWelcome
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 INFO  Session:762 - Skipping UnknownData_AllZeros
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 DEBUG Session:745 - Received 0x10: C781FEE82D794AD3E3FB5F8D096439AFB9ADDCE9
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 TRACE Session:731 - Handled PongAck {payload: 5CB33707}
Apr 14 14:35:04 raspberrypi java[512]: 2019-04-14 14:35:04 INFO  Session:707 - Skipping unknown command {cmd: 0x75, payload: 000000}
Apr 14 14:35:07 raspberrypi java[512]: 2019-04-14 14:35:07 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeHello
Apr 14 14:35:07 raspberrypi java[512]: 2019-04-14 14:35:07 TRACE MercuryClient:102 - Send Mercury request, seq: 1, uri: hm://remote/3/user/elganzua124/, method: POST
Apr 14 14:35:07 raspberrypi java[512]: 2019-04-14 14:35:07 TRACE MercuryClient:144 - Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 1
Apr 14 14:35:07 raspberrypi java[512]: 2019-04-14 14:35:07 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeHello
Apr 14 14:35:07 raspberrypi java[512]: 2019-04-14 14:35:07 INFO  Session:257 - Authenticated as elganzua124!
Apr 14 14:35:07 raspberrypi java[512]: 2019-04-14 14:35:07 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeGoodbye
Apr 14 14:35:07 raspberrypi java[512]: 2019-04-14 14:35:07 TRACE MercuryClient:102 - Send Mercury request, seq: 2, uri: hm://remote/3/user/elganzua124/, method: POST
Apr 14 14:35:07 raspberrypi java[512]: 2019-04-14 14:35:07 TRACE MercuryClient:144 - Handling packet, cmd: MercuryEvent, seq: -4813476088938233856, flags: 1, parts: 2
Apr 14 14:35:07 raspberrypi java[512]: 2019-04-14 14:35:07 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeNotify, ident: 5cb47ac01a53bc678d2a526fba14838b03a68812
```

**Comment by devgianlu** [comment] 2019-04-15 13:21
Yup, this looks like a duplicate of #77. Please post the details there.

**Closed by devgianlu** 2019-04-15 13:21 UTC
